name: 'Formal Verification Runner'
description:
  'Runs formal verification using Halmos on the generated formal specs.'
author: 'The Digital Defense Company'

outputs:
  verification_result:
    description: 'Result of the formal verification'

runs:
  using: docker
  image: Dockerfile
