name: Formal Verification Runner Demo

# This workflow will only run when manually triggered
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  verify:
    name: Run Formal Verification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: user/formal-verification-runner:latest

      - name: Run Formal Verification Runner
        id: run-verification
        uses: ./ # Use the local action
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Output
        run:
          'echo "Verification Result: ${{
          steps.run-verification.outputs.verification_result }}"'
